apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: red
  name: secret-manager
rules:
- apiGroups:
  - "" # indicates the core API group
  resources:
    - secrets
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: blue
  name: secret-manager
rules:
- apiGroups:
  - "" # indicates the core API group
  resources:
    - secrets
  verbs:
    - get
    - list